import type { AtlasDataset } from "./atlas/types";

/**
 * A deliberately rich, read-only archive for Demo Mode. The Banda–Chama story is
 * fictional, but every record is written as a small piece of a coherent family history.
 */
export const demoAtlasDataset: AtlasDataset = {
  vault: {
    name: "The Banda–Chama Family Archive",
    description: "Letters, photographs, recipes and voices following one family from the railway years to the present day.",
    ownerId: "demo",
    memberIds: ["samuel", "beatrice", "martha", "joseph", "agnes", "edward", "ruth", "daniel", "chungu", "tapiwa", "linda", "miles", "nandi", "malia", "theo"],
    coverImageUrl: null,
    createdAt: null,
    updatedAt: null,
  } as never,
  members: [
    { id: "samuel", fullName: "Samuel Banda", relationship: "Root ancestor · teacher", parentId: null, birthYear: 1897, deathYear: 1964, portraitUrl: null, notes: "A railway clerk turned village teacher who saved every letter he received in a blue tin trunk.", createdAt: null, updatedAt: null },
    { id: "beatrice", fullName: "Beatrice Phiri Banda", relationship: "Root ancestor · seamstress", parentId: null, birthYear: 1901, deathYear: 1982, portraitUrl: null, notes: "Samuel’s wife. Her embroidered tablecloth became the quiet centrepiece of family celebrations.", createdAt: null, updatedAt: null },
    { id: "martha", fullName: "Martha Banda Chama", relationship: "Daughter · gardener", parentId: "samuel", birthYear: 1921, deathYear: 2008, portraitUrl: null, notes: "Known for an open door, a formidable garden, and Sunday lunches that lasted until dusk.", createdAt: null, updatedAt: null },
    { id: "joseph", fullName: "Joseph Banda", relationship: "Son · surveyor", parentId: "samuel", birthYear: 1924, deathYear: 1999, portraitUrl: null, notes: "He carried the family archive across borders and recorded every journey in small field notebooks.", createdAt: null, updatedAt: null },
    { id: "agnes", fullName: "Agnes Banda Mwila", relationship: "Daughter · nurse", parentId: "samuel", birthYear: 1928, deathYear: 2011, portraitUrl: null, notes: "The family’s first nurse, remembered for writing practical advice in the margins of recipe books.", createdAt: null, updatedAt: null },
    { id: "edward", fullName: "Edward Chama", relationship: "Martha’s husband · mechanic", parentId: null, birthYear: 1919, deathYear: 1991, portraitUrl: null, notes: "A patient mechanic who taught every child how to listen for the rhythm of an engine.", createdAt: null, updatedAt: null },
    { id: "ruth", fullName: "Ruth Banda", relationship: "Joseph’s daughter · archivist", parentId: "joseph", birthYear: 1953, deathYear: null, portraitUrl: null, notes: "The first person to label the old trunks and begin the archive’s catalogue.", createdAt: null, updatedAt: null },
    { id: "daniel", fullName: "Daniel Chama", relationship: "Martha’s son · radio producer", parentId: "martha", birthYear: 1956, deathYear: 2019, portraitUrl: null, notes: "Collected cassette interviews with relatives whenever he travelled home.", createdAt: null, updatedAt: null },
    { id: "chungu", fullName: "Chungu Chama", relationship: "Grandson · archive steward", parentId: "martha", birthYear: 1978, deathYear: null, portraitUrl: null, notes: "Digitised the blue trunk after discovering Samuel’s first school letter tucked inside a geography book.", createdAt: null, updatedAt: null },
    { id: "tapiwa", fullName: "Tapiwa Banda", relationship: "Cousin · oral historian", parentId: "ruth", birthYear: 1988, deathYear: null, portraitUrl: null, notes: "Travels with a small recorder and a list of questions left unanswered by the photographs.", createdAt: null, updatedAt: null },
    { id: "linda", fullName: "Linda Chama", relationship: "Daughter · filmmaker", parentId: "chungu", birthYear: 2004, deathYear: null, portraitUrl: null, notes: "Makes short films that turn the archive’s fragments into stories for her generation.", createdAt: null, updatedAt: null },
    { id: "miles", fullName: "Miles Chama", relationship: "Son · mapmaker", parentId: "chungu", birthYear: 2008, deathYear: null, portraitUrl: null, notes: "Draws maps of every family journey and marks the places where someone left a story behind.", createdAt: null, updatedAt: null },
    { id: "nandi", fullName: "Nandi Mwila", relationship: "Agnes’s granddaughter · chef", parentId: "agnes", birthYear: 1992, deathYear: null, portraitUrl: null, notes: "Recreated Beatrice’s recipes from faded measurements and memory.", createdAt: null, updatedAt: null },
    { id: "malia", fullName: "Malia Banda", relationship: "Tapiwa’s daughter · student", parentId: "tapiwa", birthYear: 2015, deathYear: null, portraitUrl: null, notes: "The youngest keeper of the family questions, always asking who is missing from the photographs.", createdAt: null, updatedAt: null },
    { id: "theo", fullName: "Theo Chama", relationship: "Linda’s son · newest branch", parentId: "linda", birthYear: 2025, deathYear: null, portraitUrl: null, notes: "Born into an archive already waiting to introduce him to the people who came before.", createdAt: null, updatedAt: null },
  ] as never,
  memories: [
    { id: "railway-postcard", title: "A postcard from the railway", description: "Samuel’s first known note home: three hurried lines about the smell of rain on the platform and a promise to bring back a proper atlas.", type: "letter", assetUrl: "", thumbnailUrl: null, year: 1912, dateLabel: "November 1912", location: "Livingstone, Zambia", familyMemberIds: ["samuel"], tags: ["railway", "postcard", "beginnings"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "school-letter", title: "Samuel’s first school letter", description: "Written from his first teaching post, Samuel describes the books he hopes every child in the village will one day be able to borrow.", type: "letter", assetUrl: "", thumbnailUrl: null, year: 1920, dateLabel: "May 1920", location: "Mongu, Zambia", familyMemberIds: ["samuel"], tags: ["education", "letter", "books"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "wedding-portrait", title: "Samuel and Beatrice, beneath the jacaranda", description: "A formal portrait softened by Beatrice’s almost-smile and the petals caught in the corner of the frame.", type: "photo", assetUrl: "", thumbnailUrl: null, year: 1922, dateLabel: "September 1922", location: "Kabwe, Zambia", familyMemberIds: ["samuel", "beatrice"], tags: ["wedding", "portrait", "jacaranda"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "blue-trunk-inventory", title: "The blue trunk inventory", description: "Beatrice’s careful list of what went into the trunk before the family moved: letters, an atlas, two school slates, and a hand-cranked radio.", type: "document", assetUrl: "", thumbnailUrl: null, year: 1935, dateLabel: "February 1935", location: "Kabwe, Zambia", familyMemberIds: ["beatrice", "samuel", "martha", "joseph"], tags: ["migration", "inventory", "archive"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "market-day", title: "Market day, copper light", description: "Martha and Agnes stand shoulder to shoulder at the market, each holding a basket and a secret they refused to tell the photographer.", type: "photo", assetUrl: "", thumbnailUrl: null, year: 1943, dateLabel: "July 1943", location: "Ndola, Zambia", familyMemberIds: ["martha", "agnes"], tags: ["sisters", "market", "photograph"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "edwards-radio", title: "Edward’s radio repair book", description: "A grease-marked notebook with circuits, jokes, and a note in the back: ‘Martha sings when she thinks no one is listening.’", type: "document", assetUrl: "", thumbnailUrl: null, year: 1948, dateLabel: "1948", location: "Lusaka, Zambia", familyMemberIds: ["edward", "martha"], tags: ["radio", "love", "notebook"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "first-lunch", title: "The first Sunday table", description: "The table is crowded with enamel plates, cousins, and Beatrice’s embroidered cloth—an ordinary afternoon that became a family ritual.", type: "photo", assetUrl: "", thumbnailUrl: null, year: 1951, dateLabel: "August 1951", location: "Lusaka, Zambia", familyMemberIds: ["beatrice", "martha", "joseph", "agnes", "edward"], tags: ["Sunday lunch", "food", "family gathering"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "ruths-catalogue", title: "Ruth labels the trunks", description: "Ruth’s catalogue cards give the archive its first order, beginning with ‘Letters that make people laugh’ and ending with ‘Things we still need to ask.’", type: "document", assetUrl: "", thumbnailUrl: null, year: 1961, dateLabel: "January 1961", location: "Harare, Zimbabwe", familyMemberIds: ["ruth", "joseph"], tags: ["catalogue", "archive", "questions"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "passport", title: "Joseph’s passport, stamped in motion", description: "A stamped passport documenting a journey through Harare and Bulawayo, carrying news, photographs, and a new address for the family.", type: "document", assetUrl: "", thumbnailUrl: null, year: 1967, dateLabel: "March 1967", location: "Harare, Zimbabwe", familyMemberIds: ["joseph", "ruth"], tags: ["journey", "passport", "migration"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "fair-photograph", title: "The county fair photograph", description: "Arthur is absent from the frame, but Daniel’s caption identifies every face and says this was the day the children ‘learned to be loud.’", type: "photo", assetUrl: "", thumbnailUrl: null, year: 1972, dateLabel: "October 1972", location: "Kabwe, Zambia", familyMemberIds: ["daniel", "martha", "joseph", "ruth"], tags: ["fair", "caption", "children"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "garden-audio", title: "Martha’s garden, recorded at dusk", description: "On cassette, Martha names every plant in her garden, then pauses to explain that a family grows the same way: slowly, by being tended.", type: "audio", assetUrl: "", thumbnailUrl: null, year: 1984, dateLabel: "October 1984", location: "Ndola, Zambia", familyMemberIds: ["martha", "daniel", "chungu"], tags: ["audio", "garden", "wisdom"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "recipe-card", title: "Beatrice’s impossible recipe", description: "Nandi deciphers a recipe card that says only ‘enough flour’ and ‘stir until the house smells right.’ The final line reads: ‘Make extra for neighbours.’", type: "letter", assetUrl: "", thumbnailUrl: null, year: 1988, dateLabel: "Copied in 1988", location: "Kitwe, Zambia", familyMemberIds: ["beatrice", "nandi", "agnes"], tags: ["recipe", "food", "inheritance"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "voice-of-daniel", title: "Daniel asks the room to remember", description: "A living-room recording where Daniel interviews Joseph about the move, the missing suitcase, and the song everyone knew but nobody could finish.", type: "audio", assetUrl: "", thumbnailUrl: null, year: 1993, dateLabel: "December 1993", location: "Lusaka, Zambia", familyMemberIds: ["daniel", "joseph", "ruth", "chungu"], tags: ["oral history", "cassette", "migration"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "last-lunch", title: "Martha’s last long lunch", description: "No one knew it would be the last table with everyone present. The photograph holds four generations and three different versions of the same joke.", type: "photo", assetUrl: "", thumbnailUrl: null, year: 2007, dateLabel: "December 2007", location: "Lusaka, Zambia", familyMemberIds: ["martha", "chungu", "tapiwa", "linda", "nandi"], tags: ["Sunday lunch", "four generations", "remembrance"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "blue-trunk-scan", title: "The blue trunk opens again", description: "Chungu photographs the blue trunk before scanning its contents. Beneath a school slate lies Samuel’s 1912 postcard, still sharp with rainwater stains.", type: "photo", assetUrl: "", thumbnailUrl: null, year: 2014, dateLabel: "April 2014", location: "Lusaka, Zambia", familyMemberIds: ["chungu", "linda", "miles"], tags: ["digitisation", "blue trunk", "archive"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "malia-questions", title: "Malia’s list of questions", description: "At seven, Malia writes down the questions the photographs cannot answer: Who took this? Why were they laughing? Where did the blue trunk sleep?", type: "document", assetUrl: "", thumbnailUrl: null, year: 2022, dateLabel: "November 2022", location: "Livingstone, Zambia", familyMemberIds: ["malia", "tapiwa"], tags: ["questions", "children", "future"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "oral-history", title: "Tapiwa’s walking interview", description: "Tapiwa and Ruth walk the old road in Livingstone while comparing family stories to the places where they happened, recording the gaps as carefully as the answers.", type: "audio", assetUrl: "", thumbnailUrl: null, year: 2023, dateLabel: "May 2023", location: "Livingstone, Zambia", familyMemberIds: ["tapiwa", "ruth", "malia"], tags: ["oral history", "walking interview", "place"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "lindas-film", title: "Linda’s film premiere", description: "Linda screens a six-minute film built from the archive’s letters, cassettes, and Sunday-table photographs. Theo sleeps through the applause.", type: "video", assetUrl: "", thumbnailUrl: null, year: 2025, dateLabel: "February 2025", location: "Lusaka, Zambia", familyMemberIds: ["linda", "chungu", "theo", "miles"], tags: ["film", "premiere", "next generation"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "atlas-drawing", title: "Miles maps the family routes", description: "Miles layers railway lines, garden paths, border crossings, and home addresses into one hand-drawn map titled ‘How we kept finding each other.’", type: "document", assetUrl: "", thumbnailUrl: null, year: 2026, dateLabel: "January 2026", location: "Lusaka, Zambia", familyMemberIds: ["miles", "chungu", "linda"], tags: ["map", "routes", "future"], archived: false, createdBy: "demo", createdAt: null, updatedAt: null },
  ] as never,
  stories: [
    { id: "roots", title: "The blue trunk and the promise of books", excerpt: "How a rain-stained postcard became the first page of a family archive.", body: "Samuel began saving letters because distance made details precious. More than a century later, the same small trunk teaches his descendants that an archive is not a room full of objects; it is a promise to keep asking what mattered.", memoryIds: ["railway-postcard", "school-letter", "blue-trunk-inventory", "blue-trunk-scan"], status: "published", createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "table", title: "A table large enough for everyone", excerpt: "Beatrice’s cloth, Martha’s cooking, and the ritual that taught the family how to return.", body: "The Sunday table was never about the food alone. It was the place where news became story, grief was given room, and children learned the names of people they had not yet met. Every generation added a chair.", memoryIds: ["first-lunch", "garden-audio", "recipe-card", "last-lunch"], status: "published", createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "routes", title: "Routes, stamps, and borrowed roads", excerpt: "A family in motion across Zambia and Zimbabwe, carrying its own evidence home.", body: "Joseph’s passport and Daniel’s tapes reveal a family moving for work, care, and opportunity without losing the habit of writing home. Their routes are the lines that later became Miles’s map.", memoryIds: ["ruths-catalogue", "passport", "voice-of-daniel", "oral-history", "atlas-drawing"], status: "published", createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "voices", title: "The people speaking between the photographs", excerpt: "Cassette tapes restore the humour, rhythm, and unfinished questions missing from the still images.", body: "A photograph can show who was in the room. The voices explain why someone stayed late, who sang badly, and which story changes every time it is told. The archive becomes intimate when it can answer back.", memoryIds: ["garden-audio", "voice-of-daniel", "malia-questions", "oral-history"], status: "published", createdBy: "demo", createdAt: null, updatedAt: null },
    { id: "future", title: "The next keepers", excerpt: "Linda, Miles, Malia, and Theo inherit not just memories, but a living invitation to add their own.", body: "The archive reaches forward as much as it reaches back. In a film premiere, a child’s questions, and a map drawn for someone too young to read it, the family makes room for the stories that have not happened yet.", memoryIds: ["malia-questions", "lindas-film", "atlas-drawing"], status: "published", createdBy: "demo", createdAt: null, updatedAt: null },
  ] as never,
};
